### PR TITLE
Update installation URL

### PR DESCRIPTION
**Pull request by akki**
Update download link in "Install from URL" command

### CODE REVIEW

**Comment by akki** [comment]
Hi
The build errors don't seem to be related to the changes I have suggested. Please review.

**Comment by dothebart** [comment]
Hi @akki 
Good spot! We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

We have not been able to set of an electronic system yet. Can you sign, scan and email it to cla (at) arangodb.com?

Thanks a lot
Willi

**Comment by akki** [comment]
Hi @dothebart 
I had sent a signed copy of that CLA once before [here](https://github.com/arangodb/arangodb/pull/2125#issuecomment-261256417) for the `arangodb` repository. Will that be enough or I need to send it again for this repo?
Thanks

**Comment by dothebart** [comment]
Oh, sorry overlooked that. Fur sure not!

**Comment by akki** [comment]
Thanks! :)

**Pull request merged**
